<?php

namespace AppBundle\Repository;

/**
 * ontvangstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OntvangstRepository extends \Doctrine\ORM\EntityRepository
{
}